sudo: required
services: docker
dist: bionic
group: edge
language: minimal
branches:
    only:
        - develop
        - /^snyk.*$/
        - /^dependabot.*$/
cache:
    directories:
        - node_modules
        - "$HOME/.cache/yarn"
before_script:
    - curl -sLO https://github.com/lando/lando/releases/download/v3.0.0-rc.17/lando-v3.0.0-rc.17.deb && sudo dpkg -i lando-v3.0.0-rc.17.deb
    - rm lando-v3.0.0-rc.17.deb
script:
    - lando start
    - lando yarn run update
